title = "Oslo MedGen vcfanno configuration file"

[functions]
file="vcfanno_functions.lua"

[[annotation]]
file="gnomad.genomes.v3.1.2.sites.af.vcf.bgz"
fields = ["AF", "AF_popmax"]
ops=["self", "self"]
names=["GNOMADAF", "GNOMADAF_popmax"]

[[annotation]]
file="gnomad.genomes.v3.1.sites.chrM.vcf.bgz"
fields = ["AF_hom", "AF_het", "mitotip_score", "mitotip_trna_prediction"]
ops=["self", "self", "self", "self"]
names=["GNOMAD_MTAF_hom", "GNOMAD_MTAF_het", "mitotip_score", "mitotip_trna_prediction"]

[[annotation]]
file="whole_genome_SNVs.tsv.gz"
names=["CADD"]
ops=["mean"]
columns=[6]

[[annotation]]
file="clinvar.vcf.gz"
fields=["CLNSIG", "CLNDN"]
ops=["self","self"]
names=["CLNSIG", "CLNDN"]

