title = "Oslo MedGen vcfanno configuration file"

[functions]
file="vcfanno_functions.lua"

[[annotation]]
file="gnomad.joint.v4.1.sites.af.vcf.bgz"
fields = ["AF_joint", "AF_genomes", "AF_grpmax_joint"]
ops=["self", "self", "self"]
names=["GNOMADAF_joint", "gnomadAF_genomes", "GNOMADAF_grpmax_joint"]

[[annotation]]
file="gnomad.genomes.v3.1.sites.chrM.vcf.bgz"
fields = ["AF_hom", "AF_het", "mitotip_score", "mitotip_trna_prediction"]
ops=["self", "self", "self", "self"]
names=["GNOMAD_MTAF_hom", "GNOMAD_MTAF_het", "mitotip_score", "mitotip_trna_prediction"]

[[annotation]]
file="clinvar_utf8.vcf.gz"
fields=["CLNSIG", "CLNDN"]
ops=["self","self"]
names=["CLNSIG", "CLNDN"]

[[annotation]]
file="whole_genome_SNVs.tsv.gz"
names=["CADD"]
ops=["max"]
columns=[6]

